//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_FAST
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_FAST.ws_fastSoap")]
    public interface ws_fastSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GenerarComprobanteAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirmarComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> FirmarComprobanteAsync(string RutaCertificado, string RutaComprobante, string ClaveCertificado, string Nodos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirmarComprobanteV21", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> FirmarComprobanteV21Async(string RutaCertificado, string RutaComprobante, string ClaveCertificado, string Nodos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarNotaCredito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GenerarNotaCreditoAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarNotaDebito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GenerarNotaDebitoAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenDiarioV1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ResumenDiarioV1Async(string RucEmisor, string FechaEmision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenDiarioV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ResumenDiarioV2Async(string RucEmisor, System.DateTime FechaEmision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComunicacionBaja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ComunicacionBajaAsync(string RucEmisor, string FechaEmision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> InsertarComprobanteAsync(
                    int li_codemp, 
                    string ls_rucemp, 
                    string ls_nomemp, 
                    string ls_tipodoc, 
                    int li_codcli, 
                    string ls_ruccli, 
                    string ls_nomcli, 
                    string ls_dircli, 
                    string lf_fechadoc, 
                    string ls_serdoc, 
                    string ls_nrodoc, 
                    string ls_firma, 
                    string ls_corredoc, 
                    string ls_estado, 
                    string ls_moneda, 
                    string ls_totlet, 
                    decimal ld_porigv, 
                    decimal ld_subtot, 
                    decimal ld_monigv, 
                    decimal ld_totven, 
                    int li_coddoc, 
                    decimal ld_totdesc, 
                    string ls_tiponc, 
                    string ls_docorig, 
                    string ls_serie_orig, 
                    string ls_nro_orig, 
                    string ls_corre, 
                    string ls_doc, 
                    decimal ld_mtoefe, 
                    decimal ld_mtovue, 
                    decimal ld_mtotar, 
                    string ls_fecdocmod, 
                    string ls_ot, 
                    string ls_guia, 
                    string ls_email, 
                    string ls_observ, 
                    string ls_operacion, 
                    string ls_sustento, 
                    string ls_oc, 
                    string ls_mpago, 
                    string ls_placa, 
                    string ls_ad1, 
                    string ls_ad2, 
                    string ls_ad3, 
                    string arraydetalle, 
                    string arrayvehiculo, 
                    string arrayguia, 
                    string arrayadicional, 
                    string arrayrelacionado, 
                    string arraydiscrepancias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocumentoPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> DocumentoPDFAsync(int codigo, string formato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetencionPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> RetencionPDFAsync(int codigo, string formato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocumentoZIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> DocumentoZIPAsync(string archivo, int codigo, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ObtenerHashAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteResponse> DescargarComprobanteAsync(WS_FAST.DescargarComprobanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnularComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> AnularComprobanteAsync(int li_codigo, string ls_motivo, string ls_ad1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnularRetencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Respuestas> AnularRetencionAsync(long li_codigo, string ls_motivo, int ls_ad1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidadComproabante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<string> ValidadComproabanteAsync(
                    string CodEmisor, 
                    string RucEmisor, 
                    string NomEmisor, 
                    string TipoDoc, 
                    string CodReceptor, 
                    string TipDocReceptor, 
                    string RucReceptor, 
                    string NomReceptor, 
                    string DirReceptor, 
                    string EmailReceptor, 
                    string FechaEmision, 
                    string SerieComprobante, 
                    string NroComprobante, 
                    string Correlativo, 
                    string Moneda, 
                    string TipoOperacion, 
                    string MontoEnLetras, 
                    string CalculoIgv, 
                    string Gravadas, 
                    string Gratuitas, 
                    string Inafectas, 
                    string Exoneradas, 
                    string DescuentoGlobal, 
                    string TotalIgv, 
                    string TotalVenta, 
                    string CodigoOrigen, 
                    string TipoNC, 
                    string DocOrigen, 
                    string SerieOrigen, 
                    string NroOrigen, 
                    string CorrelativoOrigen, 
                    string FechaModifica, 
                    string SustentoNC, 
                    string MontoEfectivo, 
                    string MontoVuelto, 
                    string MontoTarjeta, 
                    string OrdenTrabajo, 
                    string GuiaRemision, 
                    string Observacion, 
                    string OrdenCompra, 
                    string ModalidaPago, 
                    string Placa, 
                    string Adicional1, 
                    string Adicional2, 
                    string Adicional3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarRetencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<int> GenerarRetencionAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneradorQR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<string> GeneradorQRAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<int> GuardarComprobanteAsync(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarComprobante_Completo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<int> GuardarComprobante_CompletoAsync(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Comprobante_Actualizar_Anulados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<int> Comprobante_Actualizar_AnuladosAsync(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCorrelativo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<string> ObtenerCorrelativoAsync(string Ruc, string Tipo, string Serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarComprobanteV21", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Response> GenerarComprobanteV21Async(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.ConsultDni> ConsultaDniAsync(string Username, string Password, string nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.ConsultRuc> ConsultaRucAsync(string Username, string Password, string nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarGuiaRemision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Response> GenerarGuiaRemisionAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegenerarXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Response> RegenerarXMLAsync(string documentojson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload_ArchivoComprobantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Upload_ArchivoComprobantesResponse> Upload_ArchivoComprobantesAsync(WS_FAST.Upload_ArchivoComprobantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FormatoComprobantePDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<int> FormatoComprobantePDFAsync(long codigo_comprobante, long codigo_formato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCDRComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Message> ConsultaCDRComprobanteAsync(string RucEmpresa, string TipoDocumento, string SerieDocumento, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargarComprobanteBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteBase64Response> DescargarComprobanteBase64Async(WS_FAST.DescargarComprobanteBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnularGuiaRemision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        System.Threading.Tasks.Task<WS_FAST.Response> AnularGuiaRemisionAsync(long codigo, string motivo, string usuarioid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargarComprobante", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargarComprobanteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int li_codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ls_formato;
        
        public DescargarComprobanteRequest()
        {
        }
        
        public DescargarComprobanteRequest(int li_codigo, string ls_formato)
        {
            this.li_codigo = li_codigo;
            this.ls_formato = ls_formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargarComprobanteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargarComprobanteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DescargarComprobanteResult;
        
        public DescargarComprobanteResponse()
        {
        }
        
        public DescargarComprobanteResponse(byte[] DescargarComprobanteResult)
        {
            this.DescargarComprobanteResult = DescargarComprobanteResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuestas
    {
        
        private string mensajeField;
        
        private string tipoField;
        
        private int valorField;
        
        private long iValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long iValor
        {
            get
            {
                return this.iValorField;
            }
            set
            {
                this.iValorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message
    {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultRuc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultDni))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResponse
    {
        
        private int statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultRuc : ServiceResponse
    {
        
        private string tNroDocumentoField;
        
        private string tRazonSocialField;
        
        private string tDireccionFiscalField;
        
        private string iCodigoUbigeoField;
        
        private string tDistritoField;
        
        private string tProvinciaField;
        
        private string tDepartamentoField;
        
        private string lStatusField;
        
        private int statuscodeField;
        
        private int codeerrorField;
        
        private string messageField;
        
        private string tDireccionCompletaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tNroDocumento
        {
            get
            {
                return this.tNroDocumentoField;
            }
            set
            {
                this.tNroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tRazonSocial
        {
            get
            {
                return this.tRazonSocialField;
            }
            set
            {
                this.tRazonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tDireccionFiscal
        {
            get
            {
                return this.tDireccionFiscalField;
            }
            set
            {
                this.tDireccionFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string iCodigoUbigeo
        {
            get
            {
                return this.iCodigoUbigeoField;
            }
            set
            {
                this.iCodigoUbigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tDistrito
        {
            get
            {
                return this.tDistritoField;
            }
            set
            {
                this.tDistritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tProvincia
        {
            get
            {
                return this.tProvinciaField;
            }
            set
            {
                this.tProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string tDepartamento
        {
            get
            {
                return this.tDepartamentoField;
            }
            set
            {
                this.tDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string lStatus
        {
            get
            {
                return this.lStatusField;
            }
            set
            {
                this.lStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int statuscode
        {
            get
            {
                return this.statuscodeField;
            }
            set
            {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int codeerror
        {
            get
            {
                return this.codeerrorField;
            }
            set
            {
                this.codeerrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tDireccionCompleta
        {
            get
            {
                return this.tDireccionCompletaField;
            }
            set
            {
                this.tDireccionCompletaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultDni : ServiceResponse
    {
        
        private string tNroDocumentoField;
        
        private string tNombresField;
        
        private string tSexoField;
        
        private string fFechaNacimientoField;
        
        private int statuscodeField;
        
        private int codeerrorField;
        
        private string messageField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tNroDocumento
        {
            get
            {
                return this.tNroDocumentoField;
            }
            set
            {
                this.tNroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tNombres
        {
            get
            {
                return this.tNombresField;
            }
            set
            {
                this.tNombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tSexo
        {
            get
            {
                return this.tSexoField;
            }
            set
            {
                this.tSexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fFechaNacimiento
        {
            get
            {
                return this.fFechaNacimientoField;
            }
            set
            {
                this.fFechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int statuscode
        {
            get
            {
                return this.statuscodeField;
            }
            set
            {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int codeerror
        {
            get
            {
                return this.codeerrorField;
            }
            set
            {
                this.codeerrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response
    {
        
        private int statusCodeField;
        
        private string statusMessageField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_ArchivoComprobantes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_ArchivoComprobantesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] archivo;
        
        public Upload_ArchivoComprobantesRequest()
        {
        }
        
        public Upload_ArchivoComprobantesRequest(byte[] archivo)
        {
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_ArchivoComprobantesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_ArchivoComprobantesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Upload_ArchivoComprobantesResult;
        
        public Upload_ArchivoComprobantesResponse()
        {
        }
        
        public Upload_ArchivoComprobantesResponse(bool Upload_ArchivoComprobantesResult)
        {
            this.Upload_ArchivoComprobantesResult = Upload_ArchivoComprobantesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargarComprobanteBase64", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargarComprobanteBase64Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long CodigoComprobante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string formato;
        
        public DescargarComprobanteBase64Request()
        {
        }
        
        public DescargarComprobanteBase64Request(long CodigoComprobante, string formato)
        {
            this.CodigoComprobante = CodigoComprobante;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargarComprobanteBase64Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargarComprobanteBase64Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DescargarComprobanteBase64Result;
        
        public DescargarComprobanteBase64Response()
        {
        }
        
        public DescargarComprobanteBase64Response(byte[] DescargarComprobanteBase64Result)
        {
            this.DescargarComprobanteBase64Result = DescargarComprobanteBase64Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ws_fastSoapChannel : WS_FAST.ws_fastSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ws_fastSoapClient : System.ServiceModel.ClientBase<WS_FAST.ws_fastSoap>, WS_FAST.ws_fastSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_fastSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_fastSoapClient.GetBindingForEndpoint(endpointConfiguration), ws_fastSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_fastSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_fastSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_fastSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_fastSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_fastSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GenerarComprobanteAsync(string documentojson)
        {
            return base.Channel.GenerarComprobanteAsync(documentojson);
        }
        
        public System.Threading.Tasks.Task<string> FirmarComprobanteAsync(string RutaCertificado, string RutaComprobante, string ClaveCertificado, string Nodos)
        {
            return base.Channel.FirmarComprobanteAsync(RutaCertificado, RutaComprobante, ClaveCertificado, Nodos);
        }
        
        public System.Threading.Tasks.Task<string> FirmarComprobanteV21Async(string RutaCertificado, string RutaComprobante, string ClaveCertificado, string Nodos)
        {
            return base.Channel.FirmarComprobanteV21Async(RutaCertificado, RutaComprobante, ClaveCertificado, Nodos);
        }
        
        public System.Threading.Tasks.Task<int> GenerarNotaCreditoAsync(string documentojson)
        {
            return base.Channel.GenerarNotaCreditoAsync(documentojson);
        }
        
        public System.Threading.Tasks.Task<int> GenerarNotaDebitoAsync(string documentojson)
        {
            return base.Channel.GenerarNotaDebitoAsync(documentojson);
        }
        
        public System.Threading.Tasks.Task<string> ResumenDiarioV1Async(string RucEmisor, string FechaEmision)
        {
            return base.Channel.ResumenDiarioV1Async(RucEmisor, FechaEmision);
        }
        
        public System.Threading.Tasks.Task<string> ResumenDiarioV2Async(string RucEmisor, System.DateTime FechaEmision)
        {
            return base.Channel.ResumenDiarioV2Async(RucEmisor, FechaEmision);
        }
        
        public System.Threading.Tasks.Task<string> ComunicacionBajaAsync(string RucEmisor, string FechaEmision)
        {
            return base.Channel.ComunicacionBajaAsync(RucEmisor, FechaEmision);
        }
        
        public System.Threading.Tasks.Task<int> InsertarComprobanteAsync(
                    int li_codemp, 
                    string ls_rucemp, 
                    string ls_nomemp, 
                    string ls_tipodoc, 
                    int li_codcli, 
                    string ls_ruccli, 
                    string ls_nomcli, 
                    string ls_dircli, 
                    string lf_fechadoc, 
                    string ls_serdoc, 
                    string ls_nrodoc, 
                    string ls_firma, 
                    string ls_corredoc, 
                    string ls_estado, 
                    string ls_moneda, 
                    string ls_totlet, 
                    decimal ld_porigv, 
                    decimal ld_subtot, 
                    decimal ld_monigv, 
                    decimal ld_totven, 
                    int li_coddoc, 
                    decimal ld_totdesc, 
                    string ls_tiponc, 
                    string ls_docorig, 
                    string ls_serie_orig, 
                    string ls_nro_orig, 
                    string ls_corre, 
                    string ls_doc, 
                    decimal ld_mtoefe, 
                    decimal ld_mtovue, 
                    decimal ld_mtotar, 
                    string ls_fecdocmod, 
                    string ls_ot, 
                    string ls_guia, 
                    string ls_email, 
                    string ls_observ, 
                    string ls_operacion, 
                    string ls_sustento, 
                    string ls_oc, 
                    string ls_mpago, 
                    string ls_placa, 
                    string ls_ad1, 
                    string ls_ad2, 
                    string ls_ad3, 
                    string arraydetalle, 
                    string arrayvehiculo, 
                    string arrayguia, 
                    string arrayadicional, 
                    string arrayrelacionado, 
                    string arraydiscrepancias)
        {
            return base.Channel.InsertarComprobanteAsync(li_codemp, ls_rucemp, ls_nomemp, ls_tipodoc, li_codcli, ls_ruccli, ls_nomcli, ls_dircli, lf_fechadoc, ls_serdoc, ls_nrodoc, ls_firma, ls_corredoc, ls_estado, ls_moneda, ls_totlet, ld_porigv, ld_subtot, ld_monigv, ld_totven, li_coddoc, ld_totdesc, ls_tiponc, ls_docorig, ls_serie_orig, ls_nro_orig, ls_corre, ls_doc, ld_mtoefe, ld_mtovue, ld_mtotar, ls_fecdocmod, ls_ot, ls_guia, ls_email, ls_observ, ls_operacion, ls_sustento, ls_oc, ls_mpago, ls_placa, ls_ad1, ls_ad2, ls_ad3, arraydetalle, arrayvehiculo, arrayguia, arrayadicional, arrayrelacionado, arraydiscrepancias);
        }
        
        public System.Threading.Tasks.Task<int> DocumentoPDFAsync(int codigo, string formato)
        {
            return base.Channel.DocumentoPDFAsync(codigo, formato);
        }
        
        public System.Threading.Tasks.Task<int> RetencionPDFAsync(int codigo, string formato)
        {
            return base.Channel.RetencionPDFAsync(codigo, formato);
        }
        
        public System.Threading.Tasks.Task<string> DocumentoZIPAsync(string archivo, int codigo, string tipo)
        {
            return base.Channel.DocumentoZIPAsync(archivo, codigo, tipo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerHashAsync(int codigo)
        {
            return base.Channel.ObtenerHashAsync(codigo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteResponse> WS_FAST.ws_fastSoap.DescargarComprobanteAsync(WS_FAST.DescargarComprobanteRequest request)
        {
            return base.Channel.DescargarComprobanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteResponse> DescargarComprobanteAsync(int li_codigo, string ls_formato)
        {
            WS_FAST.DescargarComprobanteRequest inValue = new WS_FAST.DescargarComprobanteRequest();
            inValue.li_codigo = li_codigo;
            inValue.ls_formato = ls_formato;
            return ((WS_FAST.ws_fastSoap)(this)).DescargarComprobanteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> AnularComprobanteAsync(int li_codigo, string ls_motivo, string ls_ad1)
        {
            return base.Channel.AnularComprobanteAsync(li_codigo, ls_motivo, ls_ad1);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Respuestas> AnularRetencionAsync(long li_codigo, string ls_motivo, int ls_ad1)
        {
            return base.Channel.AnularRetencionAsync(li_codigo, ls_motivo, ls_ad1);
        }
        
        public System.Threading.Tasks.Task<string> ValidadComproabanteAsync(
                    string CodEmisor, 
                    string RucEmisor, 
                    string NomEmisor, 
                    string TipoDoc, 
                    string CodReceptor, 
                    string TipDocReceptor, 
                    string RucReceptor, 
                    string NomReceptor, 
                    string DirReceptor, 
                    string EmailReceptor, 
                    string FechaEmision, 
                    string SerieComprobante, 
                    string NroComprobante, 
                    string Correlativo, 
                    string Moneda, 
                    string TipoOperacion, 
                    string MontoEnLetras, 
                    string CalculoIgv, 
                    string Gravadas, 
                    string Gratuitas, 
                    string Inafectas, 
                    string Exoneradas, 
                    string DescuentoGlobal, 
                    string TotalIgv, 
                    string TotalVenta, 
                    string CodigoOrigen, 
                    string TipoNC, 
                    string DocOrigen, 
                    string SerieOrigen, 
                    string NroOrigen, 
                    string CorrelativoOrigen, 
                    string FechaModifica, 
                    string SustentoNC, 
                    string MontoEfectivo, 
                    string MontoVuelto, 
                    string MontoTarjeta, 
                    string OrdenTrabajo, 
                    string GuiaRemision, 
                    string Observacion, 
                    string OrdenCompra, 
                    string ModalidaPago, 
                    string Placa, 
                    string Adicional1, 
                    string Adicional2, 
                    string Adicional3)
        {
            return base.Channel.ValidadComproabanteAsync(CodEmisor, RucEmisor, NomEmisor, TipoDoc, CodReceptor, TipDocReceptor, RucReceptor, NomReceptor, DirReceptor, EmailReceptor, FechaEmision, SerieComprobante, NroComprobante, Correlativo, Moneda, TipoOperacion, MontoEnLetras, CalculoIgv, Gravadas, Gratuitas, Inafectas, Exoneradas, DescuentoGlobal, TotalIgv, TotalVenta, CodigoOrigen, TipoNC, DocOrigen, SerieOrigen, NroOrigen, CorrelativoOrigen, FechaModifica, SustentoNC, MontoEfectivo, MontoVuelto, MontoTarjeta, OrdenTrabajo, GuiaRemision, Observacion, OrdenCompra, ModalidaPago, Placa, Adicional1, Adicional2, Adicional3);
        }
        
        public System.Threading.Tasks.Task<int> GenerarRetencionAsync(string documentojson)
        {
            return base.Channel.GenerarRetencionAsync(documentojson);
        }
        
        public System.Threading.Tasks.Task<string> GeneradorQRAsync(int codigo)
        {
            return base.Channel.GeneradorQRAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<int> GuardarComprobanteAsync(string cadena)
        {
            return base.Channel.GuardarComprobanteAsync(cadena);
        }
        
        public System.Threading.Tasks.Task<int> GuardarComprobante_CompletoAsync(string cadena)
        {
            return base.Channel.GuardarComprobante_CompletoAsync(cadena);
        }
        
        public System.Threading.Tasks.Task<int> Comprobante_Actualizar_AnuladosAsync(string cadena)
        {
            return base.Channel.Comprobante_Actualizar_AnuladosAsync(cadena);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerCorrelativoAsync(string Ruc, string Tipo, string Serie)
        {
            return base.Channel.ObtenerCorrelativoAsync(Ruc, Tipo, Serie);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Response> GenerarComprobanteV21Async(string documentojson)
        {
            return base.Channel.GenerarComprobanteV21Async(documentojson);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.ConsultDni> ConsultaDniAsync(string Username, string Password, string nrodocumento)
        {
            return base.Channel.ConsultaDniAsync(Username, Password, nrodocumento);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.ConsultRuc> ConsultaRucAsync(string Username, string Password, string nrodocumento)
        {
            return base.Channel.ConsultaRucAsync(Username, Password, nrodocumento);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Response> GenerarGuiaRemisionAsync(string documentojson)
        {
            return base.Channel.GenerarGuiaRemisionAsync(documentojson);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Response> RegenerarXMLAsync(string documentojson)
        {
            return base.Channel.RegenerarXMLAsync(documentojson);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_FAST.Upload_ArchivoComprobantesResponse> WS_FAST.ws_fastSoap.Upload_ArchivoComprobantesAsync(WS_FAST.Upload_ArchivoComprobantesRequest request)
        {
            return base.Channel.Upload_ArchivoComprobantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Upload_ArchivoComprobantesResponse> Upload_ArchivoComprobantesAsync(byte[] archivo)
        {
            WS_FAST.Upload_ArchivoComprobantesRequest inValue = new WS_FAST.Upload_ArchivoComprobantesRequest();
            inValue.archivo = archivo;
            return ((WS_FAST.ws_fastSoap)(this)).Upload_ArchivoComprobantesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> FormatoComprobantePDFAsync(long codigo_comprobante, long codigo_formato)
        {
            return base.Channel.FormatoComprobantePDFAsync(codigo_comprobante, codigo_formato);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Message> ConsultaCDRComprobanteAsync(string RucEmpresa, string TipoDocumento, string SerieDocumento, string NumeroDocumento)
        {
            return base.Channel.ConsultaCDRComprobanteAsync(RucEmpresa, TipoDocumento, SerieDocumento, NumeroDocumento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteBase64Response> WS_FAST.ws_fastSoap.DescargarComprobanteBase64Async(WS_FAST.DescargarComprobanteBase64Request request)
        {
            return base.Channel.DescargarComprobanteBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.DescargarComprobanteBase64Response> DescargarComprobanteBase64Async(long CodigoComprobante, string formato)
        {
            WS_FAST.DescargarComprobanteBase64Request inValue = new WS_FAST.DescargarComprobanteBase64Request();
            inValue.CodigoComprobante = CodigoComprobante;
            inValue.formato = formato;
            return ((WS_FAST.ws_fastSoap)(this)).DescargarComprobanteBase64Async(inValue);
        }
        
        public System.Threading.Tasks.Task<WS_FAST.Response> AnularGuiaRemisionAsync(long codigo, string motivo, string usuarioid)
        {
            return base.Channel.AnularGuiaRemisionAsync(codigo, motivo, usuarioid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_fastSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_fastSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_fastSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.sistemafast.pe/ws_fast.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_fastSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.sistemafast.pe/ws_fast.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ws_fastSoap,
            
            ws_fastSoap12,
        }
    }
}
