using ApiLMotos.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace ApiLMotos.DbHandle
{
    public class EmpresaDb: GeneralDb
    {
        public List<Empresa> Empresas(string ruc)
        {
            List<Empresa> listEntidad = null;
            using (SqlConnection connection = new SqlConnection(Cadena))
            {
                connection.Open();
                SqlCommand command = new SqlCommand("wsp_Empresas_V48", connection);
                command.Parameters.Add("@ruc", SqlDbType.VarChar).Value = ruc;
                command.CommandType = CommandType.StoredProcedure;
                SqlDataReader reader = command.ExecuteReader(CommandBehavior.SingleResult);
                if (reader.HasRows)
                {
                    Empresa entidad = null;
                    listEntidad = new List<Empresa>();
                    while (reader.Read())
                    {
                        entidad = new Empresa();
                        entidad.Ruc = reader.GetString(0);
                        entidad.NombreEmpresa = reader.GetString(1);
                        entidad.Comercial = reader.GetString(2);
                        entidad.Direccion = reader.GetString(3);
                        entidad.Distrito = reader.GetString(4);
                        entidad.Provincia = reader.GetString(5);
                        entidad.Region = reader.GetString(6);
                        entidad.Telefono = reader.GetString(7);
                        entidad.Resolucion = reader.GetString(8);
                        entidad.Web = reader.GetString(9);
                        entidad.Email = reader.GetString(10);
                        entidad.Codigo = reader.GetString(11);
                        entidad.Perfil = reader.GetString(12);
                        entidad.Logo = reader.GetString(13);
                        entidad.Banner = reader.GetString(14);
                        entidad.Detraccion = reader.GetDecimal(15);
                        entidad.DetraccionText = reader.GetString(16);
                        entidad.Zona = reader.GetString(17);
                        entidad.INC_IGV = reader.GetBoolean(18);
                        entidad.ExoneraIgv = reader.GetBoolean(19);
                        entidad.lVistaPrevia = reader.GetBoolean(20);
                        entidad.Remision = reader.GetBoolean(21);
                        entidad.lv_PrecioUnitario = reader.GetBoolean(22);
                        entidad.lv_PrecioValor = reader.GetBoolean(23);
                        entidad.lv_PrecioVenta = reader.GetBoolean(24);
                        entidad.Requerimiento = reader.GetBoolean(25);
                        entidad.lv_IGV = reader.GetBoolean(26);
                        entidad.lv_Descuento = reader.GetBoolean(27);
                        entidad.Comprobante = reader.GetInt32(28);
                        entidad.FechaInicio = reader.GetDateTime(29);
                        entidad.FechaFin = reader.GetDateTime(30);
                        entidad.LogoExterno = reader.GetString(31);
                        entidad.UbigeoDistrito = reader.GetInt32(32);
                        entidad.UbigeoProvincia = reader.GetInt32(33);
                        entidad.UbigeoDepartamento = reader.GetInt32(34);
                        entidad.lenv_Correo_Auto = reader.GetBoolean(35);
                        entidad.lv_PlacaVehiculo = reader.GetBoolean(36);
                        entidad.lpFormula = reader.GetBoolean(37);
                        entidad.lvdObservacion = reader.GetBoolean(38);
                        entidad.lvdRedondeo = reader.GetBoolean(39);
                        entidad.lvtIGV = reader.GetBoolean(40);
                        entidad.lvpTotal = reader.GetBoolean(41);
                        entidad.lPago = reader.GetBoolean(42);
                        entidad.lImpresionAuto = reader.GetBoolean(43);
                        entidad.Alerta = reader.GetInt32(44);
                        entidad.lFactura_btn = reader.GetBoolean(45);
                        entidad.nIGV = reader.GetDecimal(46);
                        entidad.nIGVUNI = reader.GetDecimal(47);
                        entidad.lAlmacen = reader.GetBoolean(48);
                        entidad.lSucursal = reader.GetBoolean(49);
                        entidad.S_BuenContribuyente = reader.GetBoolean(50);
                        entidad.lVehiculo = reader.GetBoolean(51);
                        entidad.lSegundaLinea = reader.GetBoolean(52);
                        entidad.lEliminaComprobante = reader.GetBoolean(53);
                        entidad.lDescuento = reader.GetBoolean(54);
                        entidad.lVentaMayor = reader.GetBoolean(55);
                        entidad.lTransporte = reader.GetBoolean(56);
                        entidad.lAnticipo = reader.GetBoolean(57);
                        entidad.lAgenteDetraccion = reader.GetBoolean(58);
                        entidad.lVistaPreviaCotizacion = reader.GetBoolean(59);
                        entidad.lHotel = reader.GetBoolean(60);
                        entidad.lSeguimientoCotizacion = reader.GetBoolean(61);
                        entidad.lRedondeo = reader.GetBoolean(62);
                        entidad.lMoneda = reader.GetBoolean(63);
                        entidad.lPeso_Cotizacion = reader.GetBoolean(64);
                        entidad.lCotizacion = reader.GetBoolean(65);
                        entidad.tVersion = reader.GetString(66);
                        entidad.lVendedorDesbloqueado = reader.GetBoolean(67);
                        entidad.lv_DescuentoPorcentaje = reader.GetBoolean(68);
                        entidad.lEmbarcacionPesquera = reader.GetBoolean(69);
                        entidad.lLiquidacion = reader.GetBoolean(70);
                        entidad.lTicket = reader.GetBoolean(71);
                        entidad.lNaval = reader.GetBoolean(72);
                        entidad.lv_DescuentoUnidad = reader.GetBoolean(73);
                        entidad.tEmpUsuario = reader.GetString(74);
                        entidad.tEmpClave = reader.GetString(75);
                        entidad.lVPCompra = reader.GetBoolean(76);
                        entidad.lVPVenta = reader.GetBoolean(77);
                        entidad.lCalculoInverso = reader.GetBoolean(78);
                        entidad.lPasajero = reader.GetBoolean(79);
                        entidad.lv_ObsServicio = reader.GetBoolean(80);
                        entidad.nDiasEmision = reader.GetInt32(81);
                        entidad.fFechaActual = reader.GetString(82);
                        entidad.lv_GuiaTransporte = reader.GetBoolean(83);
                        entidad.Oblig_PlacaVehiculo = reader.GetBoolean(84);
                        entidad.lv_PrecioEditable = reader.GetBoolean(85);
                        entidad.lRegularizarAlmacen = reader.GetBoolean(86);
                        entidad.lProductoSunat = reader.GetBoolean(87);
                        entidad.lIncluyePercepcion = reader.GetBoolean(88);
                        entidad.lVendedorComp = reader.GetBoolean(89);
                        //entidad.tEmpUsuario = entidad.tEmpUsuario != "" ? Cryptography.DecryptSunat(entidad.tEmpUsuario) : entidad.tEmpUsuario;
                        //entidad.tEmpClave = entidad.tEmpClave != "" ? Cryptography.DecryptSunat(entidad.tEmpClave) : entidad.tEmpClave;
                        entidad.lAlmacenNegativo = reader.GetBoolean(90);
                        entidad.lVerStock = reader.GetBoolean(91);
                        entidad.lCodigoBarra = reader.GetBoolean(92);
                        entidad.lLote = reader.GetBoolean(93);
                        entidad.lCotizacionMovimiento = reader.GetBoolean(94);
                        entidad.lCaja = reader.GetBoolean(95);
                        entidad.lOrdenVenta = reader.GetBoolean(96);
                        entidad.lCajaOrdenVenta = reader.GetBoolean(97);
                        entidad.lCobroAntes = reader.GetBoolean(98);
                        entidad.lMargenGanancia = reader.GetBoolean(99);
                        entidad.nPorcentajeMargen = reader.GetDecimal(100);
                        entidad.lProductoBuscar_Auto = reader.GetBoolean(101);
                        entidad.lPdfTxt = reader.GetBoolean(102);
                        entidad.lOrdenServicio = reader.GetBoolean(103);
                        entidad.lFactorGanancia = reader.GetBoolean(104);
                        entidad.nFactorPorcentaje = reader.GetDecimal(105);
                        entidad.lConversionMoneda = reader.GetBoolean(106);
                        entidad.lVentasPromocion = reader.GetBoolean(107);
                        entidad.iVentasPromocionCantidad = reader.GetInt32(108);
                        entidad.iPrecioCompraDecimales = reader.GetInt32(109);
                        entidad.nPorcentajeRC = reader.GetDecimal(110);
                        entidad.lSelectProducto = reader.GetBoolean(111);
                        entidad.lProductoEquivalencia = reader.GetBoolean(112);
                        entidad.lContratoVehiculo = reader.GetBoolean(113);
                        entidad.lBuscarClienteCodigo = reader.GetBoolean(114);
                        entidad.lAddCodBarraAuto = reader.GetBoolean(115);
                        entidad.lZona = reader.GetBoolean(116);
                        entidad.lDrogueria = reader.GetBoolean(117);
                        entidad.lVerPrecioVentaSoles = reader.GetBoolean(118);
                        entidad.lImpresionMasivo = reader.GetBoolean(119);
                        entidad.lVerButtonPDFCDP = reader.GetBoolean(120);
                        entidad.lCursorCantidadDetalle = reader.GetBoolean(121);
                        entidad.INC_IGV_Compra = reader.GetBoolean(122);
                        entidad.INC_IGV_Producto = reader.GetBoolean(123);
                        entidad.lConVentaBtnCorreo = reader.GetBoolean(124);
                        entidad.lFechaEntregaCoti = reader.GetBoolean(125);
                        entidad.lNumAutogeneradoCotizacion = reader.GetBoolean(126);
                        entidad.lCotizacionPrincipal = reader.GetBoolean(127);
                        entidad.lDistribuidor = reader.GetBoolean(128);
                        entidad.lvd_TipoAfectacion = reader.GetBoolean(129);
                        entidad.ldv_CodigoProducto = reader.GetBoolean(130);
                        entidad.lGuiaRemisionManual = reader.GetBoolean(131);
                        entidad.lPrecioAplicarUpdate = reader.GetBoolean(135);
                        entidad.lMostrarSinStock = reader.GetBoolean(136);
                        entidad.lVentaAlmacen = reader.GetBoolean(137);
                        entidad.lFechaVencimiento = reader.GetBoolean(138);
                        entidad.lCodigoClienteProducto = reader.GetBoolean(139);
                        entidad.lMarca = reader.GetBoolean(140);
                        entidad.lCaracteristicasAdicionales = reader.GetBoolean(141);
                        entidad.lColor = reader.GetBoolean(142);
                        entidad.lEncomiendaTransporte = reader.GetBoolean(143);
                        entidad.lBoletoControlTransporte = reader.GetBoolean(144);
                        entidad.ldv_CantCaja = reader.GetBoolean(145);
                        entidad.lPdfAdicional = reader.GetBoolean(146);
                        entidad.lImpresionRapidaComanda = reader.GetBoolean(147);
                        entidad.lAplicaCuota = reader.GetBoolean(148);
                        entidad.lResAvanceSucursal = reader.GetBoolean(149);
                        entidad.iRestauranteVista = reader.GetInt32(150);
                        entidad.lCompraDetalle = reader.GetBoolean(151);
                        entidad.lCompraNotaIngreso = reader.GetBoolean(152);
                        entidad.tRutaLogo = reader.GetString(153);
                        entidad.tRutaBanner = reader.GetString(154);
                        entidad.tRutaLogoExt = reader.GetString(155);
                        entidad.lvdObservacionAlmacen = reader.GetBoolean(156);
                        //entidad.lPrepagoRestaurante = reader.GetBoolean(157);
                        entidad.lBarraLibreRestaurante = reader.GetBoolean(158);
                        entidad.lFechaVencimientoProducto = reader.GetBoolean(159);
                        entidad.lFechaNotaVentaPeriodo = reader.GetBoolean(160);
                        entidad.lGuiaRemitenteButton = reader.GetBoolean(161);
                        entidad.lGuiaRemitenteVistaPrevia = reader.GetBoolean(162);
                        entidad.lExportacionOtros = reader.GetBoolean(163);
                        entidad.lDocumentoRelacionadoCompras = reader.GetBoolean(164);
                        entidad.lProductoImagePath = reader.GetBoolean(165);
                        entidad.lIgnorarCajaOrdenVenta = reader.GetBoolean(166);
                        entidad.lMonedaUSDProducto = reader.GetBoolean(167);
                        entidad.lMonedaUSDIngreso = reader.GetBoolean(168);
                        entidad.lUncheckPagado = reader.GetBoolean(254);
                        entidad.lCalcularDetraccion = reader.GetBoolean(275);
                        entidad.lCalcularRetencionIgv = reader.GetBoolean(277);
                        listEntidad.Add(entidad);
                    }
                }
                reader.Close();
                connection.Close();
            }
            return listEntidad;
        }
    }
}
